spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_microservices
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  jwt:
    keystore:
      path: keystore/sms.jks
      alias: sms
