spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://postgres:5432/spring_microservices
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
