version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring_microservices

  eureka-discovery-service:
    container_name: eureka-discovery-service
    image: openjdk:11.0.9.1-jdk
    ports:
      - 8761:8761
    volumes:
      - ./eureka-discovery-service:/usr/src/app
    working_dir: /usr/src/app
    command: ./mvnw spring-boot:run

  zuul-gateway-service:
    container_name: zuul-gateway-service
    image: openjdk:11.0.9.1-jdk
    ports:
      - 8765:8765
    volumes:
      - ./zuul-gateway-service:/usr/src/app
    working_dir: /usr/src/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--eureka.client.serviceUrl.defaultZone=http://eureka-discovery-service:8761/eureka"
    depends_on:
      - eureka-discovery-service

  config-service:
    container_name: config-service
    image: openjdk:11.0.9.1-jdk
    ports:
      - 1000:1000
    volumes:
      - ./config-service:/usr/src/app
    working_dir: /usr/src/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--eureka.client.serviceUrl.defaultZone=http://eureka-discovery-service:8761/eureka"
    depends_on:
      - eureka-discovery-service
      - zuul-gateway-service

  authorization-service:
    container_name: authorization-service
    image: openjdk:11.0.9.1-jdk
    environment:
      CONFIG_SERVICE: http://zuul-gateway-service:8765/config-service
    ports:
      - 1001:1001
    volumes:
      - ./authorization-service:/usr/src/app
    working_dir: /usr/src/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--eureka.client.serviceUrl.defaultZone=http://eureka-discovery-service:8761/eureka,--spring.cloud.config.git.uri=http://zuul-gateway-service:8765/config-service"
    depends_on:
      - postgres
      - eureka-discovery-service
      - zuul-gateway-service
      - config-service

  user-service:
    container_name: user-service
    image: openjdk:11.0.9.1-jdk
    environment:
      CONFIG_SERVICE: http://zuul-gateway-service:8765/config-service
    ports:
      - 1002:1002
    volumes:
      - ./user-service:/usr/src/app
    working_dir: /usr/src/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--eureka.client.serviceUrl.defaultZone=http://eureka-discovery-service:8761/eureka,--spring.cloud.config.git.uri=http://zuul-gateway-service:8765/config-service"
    depends_on:
      - postgres
      - eureka-discovery-service
      - zuul-gateway-service
      - config-service
