version: '3'
services:
  eureka-discovery:
    image: eureka-discovery-service:0.0.1
    ports:
      - 8761:8761
  zuul-gateway:
    image: zuul-gateway-service:0.0.1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-discovery:8761/eureka
    depends_on:
      - eureka-discovery
    ports:
      - 8765:8765
  config:
    image: config-service:0.0.1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-discovery:8761/eureka
    depends_on:
      - eureka-discovery
    ports:
      - 1000:1000
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring_microservices
    ports:
      - 5432:5432
  authorization-service:
    image: authorization-service:0.0.1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-discovery:8761/eureka
      - spring.cloud.config.uri=http://zuul-gateway:8765/config-service
    depends_on:
      - postgres
      - eureka-discovery
      - config
      - zuul-gateway
    links:
      - postgres
    ports:
      - 1001:1001