spring:
  application:
    name: photo-app-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/photo_app
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
