spring:
  application:
    name: photo-app-user-service
  h2:
    console:
      settings:
        web-allow-others: true

server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
