spring:
  profiles:
    active: dev
  application:
    name: zuul-gateway-service

server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  ReadTimeout: 10000
