spring:
  profiles:
    active: dev
  application:
    name: zuul-gateway-service
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: 'http://localhost:8765/authorization-service/oauth/check_token'
          client-id: 'client'
          client-secret: 'pass'
        jwt:
          public-key-location: classpath:keystore/sms-pub.pem
server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  ReadTimeout: 10000

