spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mfgabriel92/spring-microservices/config-service

server:
  port: 8191
