spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mfgabriel92/spring-microservices
          search-paths:
            - 'config-service/src/main/resources/*service/'
      fail-fast: true
      retry:
        initial-interval: 1500
        multiplier: 1.5
        max-attempts: 10000
        max-interval: 1000

server:
  port: 0

eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 10